import '../(home)/globals.css';
import { Toaster } from '@/components/ui/toaster';
export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex justify-center items-center min-h-screen'>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
