import '../globals.css';
import { Toaster } from '@/components/ui/toaster';
import Footer from '../../components/Footer';
import { MountainIcon } from '../../components/icons';
import Link from 'next/link';
import StoreProvider from '../../components/providers/StoreProvider';
export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className='flex flex-col  min-h-screen'>
      <StoreProvider>
        <header className='bg-background border-b shadow-sm sticky top-0 z-30 flex justify-center'>
          <div className='container px-4 md:px-6 flex items-center h-14 lg:h-16'>
            <Link
              href='/'
              className='mr-6 flex items-center gap-2'
              prefetch={false}
            >
              <MountainIcon className='h-6 w-6' />
              <span className='text-lg font-semibold'>Acme Ecommerce</span>
            </Link>
          </div>
        </header>
        {children}
        <Toaster />
        <Footer />
      </StoreProvider>
    </div>
  );
}
