import { Toaster } from '../components/ui/toaster';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        {children}

        <Toaster />
      </body>
    </html>
  );
}
