import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import { cn } from '@/lib/utils';
import '../globals.css';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import StoreProvider from '../../components/providers/StoreProvider';

const fontHeading = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
});

const fontBody = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
});

export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={cn(
        'antialiased flex flex-col min-h-screen',
        fontHeading.variable,
        fontBody.variable,
      )}
    >
      <StoreProvider>
        <Header />
        {children}
        <Footer />
      </StoreProvider>
    </div>
  );
}
